### ISSUE TITLE
Advertise quilt support on modrinth

### ISSUE THREAD

**Issue by CuteistCat** [Avanatiker/WorldTools#10]
Untill modrinth makes ther launcher accept fabric mods for auttoupdateing on quilt if they dont advetise quilt support this will be very usefull

**Comment by Avanatiker** [comment]
sorry iam not that into quilt can you explain in more depth?

**Comment by CuteistCat** [comment]
Quilt haz full soppurt for nearly all fabric mods(it works whith d=this one), Modrinth launcher dosent no that and such to instsll world tools on quilt u have to hit overright loaders,fabric,then workdtools,and select the right version.If u would mark it as compatible with quilt the same way u mark it as compatible with fabric on modrinths website than We dont have to di as much work to install world tools on modrinth launcher and it will be autoupdating

**Comment by CuteistCat** [comment]
Quilt has there own Completly compatible implementation of the fabric api name "quilted fabric api"(or QFAPI) that is based on there QSL but the QFAPI haz not updated passed 1.20.1 so untill it gets updated to new versions dont have post 1.20.1 versions marked as quilt compatible if they use the fabric api

**Comment by Avanatiker** [comment]
all right thanks for the explanation. it should be marked now :) https://modrinth.com/mod/worldtools/version/1.1.1
