### ISSUE TITLE
1.20.4 Support?

### ISSUE THREAD

**Issue by DartPower** [Avanatiker/WorldTools#11]
Can you implement 1.20.4 support?

**Comment by Avanatiker** [comment]
Supporting more versions is planned but will take some time.

**Comment by rfresh2** [comment]
1.20.4 builds are available on github actions: https://github.com/Avanatiker/WorldTools/actions?query=branch%3A1.20.4++

**Comment by rfresh2** [comment]
1.20.4 support released: https://github.com/Avanatiker/WorldTools/releases/tag/1.2.0%2B1.20.1
