### ISSUE TITLE
Data in chests and command blocks do not save.

### ISSUE THREAD

**Issue by iXmaxGames** [Avanatiker/WorldTools#13]
Items in chests and commands in command blocks do not save using WorldTools Fabric 1.1.1. 

MC Version:
- fabric-loader-0.15.3-1.20.1

Mods:
- cloth-config-11.1.118-fabric
- fabric-api-0.91.0+1.20.1
- fabric-language-kotlin-1.10.17+kotlin.1.9.22
- modmenu-7.2.2
- WorldTools-fabric-1.1.1

**Comment by rfresh2** [comment]
Resolved in:

* 1.20.1: https://github.com/Avanatiker/WorldTools/commit/db8d44eaef2ecf0f2d8396d614ac551a460b4ec6
* 1.20.4: https://github.com/Avanatiker/WorldTools/commit/958fc4cf9db257fbfb200a5f67342eca446d3ba7
