### ISSUE TITLE
Version 1.1.1 is incompatible with MysteryMod-1.20.1-1.0.1.jar Mod. - 1.0.0 runs fine

### ISSUE THREAD

**Issue by CypherXG** [Avanatiker/WorldTools#14]
Hi
Griefergames.net Server uses this addon to add more Blocks and many more features.
The Problem that i have is:
When i use my regular mods also with MysteryMod-1.20.1-1.0.1.jar and your old Version 1.0.0 the Worlddownloader runs, but it has no  GUI etc. but i can download Maps.
If i use the new 1.1.1 Version the client crashes with the MystMod addon.
I try to find out what's exactly happen but im not a java developer ^^

Here is my crash report and the log:
[crash-2024-01-13_08.55.28-client.txt](https://github.com/Avanatiker/WorldTools/files/13927485/crash-2024-01-13_08.55.28-client.txt)
[2024-01-13-3.log](https://github.com/Avanatiker/WorldTools/files/13927487/2024-01-13-3.log)

Maybe you will find out something

Best regards
Fizzy Bubbele

**Comment by rfresh2** [comment]
This is caused by MysteryMod shading the entire Kotlin standard library instead of using the standard `fabric-language-kotlin` library. 

Why they would do this is truly a _mystery_ to me

**Comment by Avanatiker** [comment]
Those "buy-cosmetics" mods like Badlion, Labymod etc are mostly complete trash in terms of software quality. I do not recommend using them at all as they only target your money. I cant fix that because its an issue of MysteryMod not following good practices.
