### ISSUE TITLE
When will there be 1.20.2 support?

### ISSUE THREAD

**Issue by michiel1106** [Avanatiker/WorldTools#15]
Hey im wondering when/if there will be a 1.20.2 support. would really appreciate it.

**Comment by P529** [comment]
The 1.20.2 support is currently in development :)

**Comment by Avanatiker** [comment]
Actually 1.20.4 is that ok too?

**Comment by michiel1106** [comment]
> Actually 1.20.4 is that ok too?

Would prefer 1.20.2 as thats the version this specific server is on. But its your mod so what do you want do?

**Comment by P529** [comment]
> > Actually 1.20.4 is that ok too?
> 
> Would prefer 1.20.2 as thats the version this specific server is on. But its your mod so what do you want do?

Once the 1.20.4 version is released you'll be able to use it with Via to connect to 1.20.2 servers as well :)

**Comment by rfresh2** [comment]
Added 1.20.2 support: https://github.com/Avanatiker/WorldTools/tree/1.20.2

Until a release is published, you can download it from github actions: https://github.com/Avanatiker/WorldTools/actions/runs/7791889849

1.20.4 builds are available similarly

**Comment by rfresh2** [comment]
1.20.2 support released: https://github.com/Avanatiker/WorldTools/releases/tag/1.2.0%2B1.20.1
