### ISSUE TITLE
Unable to save Map data

### ISSUE THREAD

**Issue by Radaggon** [Avanatiker/WorldTools#16]
Hey! I am looking for a way to WDL a mapart outpost on a server! When using this tool I only have blank maps even though their names are accurately downloaded.
I tried on 2b2t an another random creative server and ended up with the same results.

Thanks for looking into this, have a good one!

**Comment by Imnotcanhuxi** [comment]
我也是一样
I am the same

**Comment by rfresh2** [comment]
Resolved in: 

* 1.20.1: https://github.com/Avanatiker/WorldTools/commit/55060af79a634b47b7662cc6b1671f32600f47b4
* 1.20.4: https://github.com/Avanatiker/WorldTools/commit/bd8279c6253a19920c744f50e692e87857d08050
