### ISSUE TITLE
Containers not always saving on Mac

### ISSUE THREAD

**Issue by CecilTheTurtle** [Avanatiker/WorldTools#17]
Having issues with saving containers on a Mac. I have future, rusher and meteor and when I added world tools I got a lot of crashing. removing future seemed to have fixed things. after removing future on 1.20.1 it would save the world, but not containers. Updated everything to 1.20.4 and have better luck with saving containers, but not consistent. It registers every container, but not every container's contents was saved in the wdl. Is there a speed issue with saving containers?

**Comment by rfresh2** [comment]
> when I added world tools I got a lot of crashing

Please provide latest.log files of the crashes

> it would save the world, but not containers.

What we need is a way to replicate your issue. So some combination or one of a video, world download, or instructions.

**Comment by CecilTheTurtle** [comment]
I will see if I can get you a world download, and I am working on getting reproducible steps.

**Comment by Avanatiker** [comment]
Can you try again on latest versions?

**Comment by CecilTheTurtle** [comment]
It’s been much better. I need to update to 1.2.4. will do so soon. 

	-Kevin

**Comment by CecilTheTurtle** [comment]
I think you can call this resolved. Seems to be working well with 1.2.4

	Thanks,
		Cecil
