### ISSUE TITLE
How to hide the process bar?

### ISSUE THREAD

**Issue by APRme** [Avanatiker/WorldTools#22]
![image](https://github.com/Avanatiker/WorldTools/assets/124433148/0be134cf-c870-411b-ad15-6e02fb997106)
I didn't find any options to hide them when downloading the world.

**Comment by rfresh2** [comment]
There is no setting to disable it currently, but that can be added in a future update

**Comment by Avanatiker** [comment]
Any reason why you would like to hide it?
