### ISSUE TITLE
F12 Menu does not show up and sometimes multiple servers have chunks saved to the same file(Fabric)

### ISSUE THREAD

**Issue by BookWyrm114** [Avanatiker/WorldTools#3]
1: I noticed last night that pressing F12 blurs the background, and acts as if I am in a menu, but no buttons or anything else are rendered. I do not know what is causing this, but my best guess is that it may be a conflict with [https://modrinth.com/mod/modern-ui](https://modrinth.com/mod/modern-ui)

2: I also noticed that the mod will write world data to a save periodically, and leaving a server does not clear this, and since the mod seems to start automatically upon joining a server, and will automatically continue immediately after writing world data to a save, it seems that, after the first server you join, there will always be at least a bit of world data carried over from the last server to the next, which can cause missing or mixed chunks, and having 2 different world saves for the same server, as the first time it writes the world data, it counts it as using the address of the previous server, but not the second write, so you'll have one save of mixed chunks, then another that contains any chunks _except_ the chunks that you saved first, so it will usually be missing the spawn chunks

I currently am not at my PC so I can't test for mod conflicts and such, but will do so later.

Also, thanks for making this mod, I quite believed that a World Downloader mod for modern versions was impossible (excluding the minecraft world downloader that runs as an external app but that's not nearly as useful as a client-sided mod, and significantly more buggy), I haven't tested this out yet, and I'd assume it probably does, but does this work with mods such as ViaFabricPlus? As that would allow downloading worlds from older servers without needing to develop the WorldTools mod for any version of the game besides the newest version.

**Comment by VideoGameSmash12** [comment]
> 1: I noticed last night that pressing F12 blurs the background, and acts as if I am in a menu, but no buttons or anything else are rendered. I do not know what is causing this, but my best guess is that it may be a conflict with https://modrinth.com/mod/modern-ui

This is not just an issue with Modern UI - I have the mod running myself and the menu simply doesn't render for some reason. Judging from the source code, it's entirely possible that the menu itself hasn't been implemented yet - https://github.com/Avanatiker/WorldTools/blob/master/common/src/main/kotlin/org/waste/of/time/gui/WorldToolsScreen.kt

**Comment by BookWyrm114** [comment]
Thanks, that’s quite useful! And hopefully the menu is implemented soon then if that’s the case.

**Comment by Avanatiker** [comment]
Thanks @VideoGameSmash12 for that detailed answer. Indeed the GUI was not implemented in the latest release. The latest nightlies have one now and i will make a release very soon. Also configs and much more :)
