### ISSUE TITLE
Request Add a way to force disable mod at serverjoin

### ISSUE THREAD

**Issue by CraftJunkies** [Avanatiker/WorldTools#32]
Please implement a way to force deactivate the mod on serverjoin when the server sends a certain colourcode combination to the client like with the voxelmap.

**Comment by rfresh2** [comment]
this mod is open source. any protections built into this mod would be trivially removable in a fork. 

I'm sympathetic to server owners having their maps stolen, but the MC protocol does not hide this data at all. For example, even with a DRM thing built-in, players could capture a ReplayMod recording, then open that recording in WorldTools and download the map there. Basically its impossible to actually prevent.

Similar discussion on alternative WDL tools: https://github.com/mircokroon/minecraft-world-downloader/issues/63

**Comment by Avanatiker** [comment]
Well said

**Comment by joeyjumper94** [comment]
you should add it. as without a way for server owners to automatically tell clients to not download their map, server owners may simply resort to automatically banning people when this mod is detected.
