### ISSUE TITLE
1.21 pls

### ISSUE THREAD

**Issue by UnderQuestion** [Avanatiker/WorldTools#35]

**Comment by rfresh2** [comment]
for now you can download it here: https://github.com/Avanatiker/WorldTools/actions/runs/9508281414

Click on "Artifacts" to get the jar

**Comment by Redhawk18** [comment]
but there should be a release so clients can download it from their mod menu

**Comment by Avanatiker** [comment]
https://github.com/Avanatiker/WorldTools/releases/tag/1.2.5%2B1.21.1
