### ISSUE TITLE
中文翻译Chinese translation

### ISSUE THREAD

**Issue by OolongMC** [Avanatiker/WorldTools#36]
我将这个模组翻译为了中文（Chat GPT 4o翻译+人工校对），文件如下，希望能将此文件放入此MOD中。
I translated this module into Chinese (Chat GPT 4o translation+manual proofreading). The file is as follows. I hope this file can be put into this MOD.

文件见'zh_cn.json'（语言：中文（简体）   版本适配：WorldTools-fabric-1.2.4+1.20.1）
See' zh_cn.json' for the file (language: Chinese (simplified)   version adaptation: WorldTools-fabric-1.2.4+1.20.1).
[zh_cn.json](https://github.com/user-attachments/files/16047545/zh_cn.json)

**Comment by Avanatiker** [comment]
Hey i just merged anther translation https://github.com/Avanatiker/WorldTools/commit/178f0200978e2af28a9213c350e11fdd1d8f25d5 it was made a little earlier than yours. do you guys aprove? @MCdiax @OolongMC

**Comment by OolongMC** [comment]
> Hey i just merged anther translation [178f020](https://github.com/Avanatiker/WorldTools/commit/178f0200978e2af28a9213c350e11fdd1d8f25d5) it was made a little earlier than yours. do you guys aprove? @MCdiax @OolongMC

This translation is good.There are also some humorous words in it.Such as '撅首者'.And I translated it as "循声守卫".I changed the word "capture" to "Download" which is easier for China people to understand. And this translation still uses "capture".This is closer to this Mod.
In the end,My idea is "whatever".=)

**Comment by Avanatiker** [comment]
All right thank you again for you work guys! <3 (we have traditional chinese aswell now btw: https://github.com/Avanatiker/WorldTools/pull/49)
