### ISSUE TITLE
Config option not effective?

### ISSUE THREAD

**Issue by ghost** [Avanatiker/WorldTools#46]
Hi. I use this mod to capture and archive some server maps, however there are some potentional issues I think. I use Minecraft 1.21, Fabric loader, with ViaFabricPlus 3.4.5 and a modified fork version of WorldTools from https://github.com/RyuguDev/WorldTools-1.21.1 (PR https://github.com/Avanatiker/WorldTools/pull/45). I join a 1.8 server on 1.21 client with the help of ViaFabricPlus. 

The server, as far as I know, utilizes some hacky approaches to send custom packets. As shown in this picture, partially because of ViaFabricPlus, a fake, invisible wither entity can be seen. In addition, a fake ender dragon entity lies below, which is always pined at an y and follows player's x and z:

![1](https://github.com/user-attachments/assets/ebf251df-7d93-45b4-a110-28edfd8fac24)

![2](https://github.com/user-attachments/assets/fca910ba-9fc9-4126-8f99-8edb4b76a9e8)

I walk around to capture all the chunks I could reach. Chunks capture is successful, yet tons of redundant, unwanted entities are captured as well. As a result, I have to run `/kill` twice:

![3](https://github.com/user-attachments/assets/814f941f-240f-4bb1-93d9-c09cdbe499b4)

![4](https://github.com/user-attachments/assets/a0960d55-dd39-4831-ae4e-7d89705066e3)

![5](https://github.com/user-attachments/assets/e4f740b5-ab84-4d88-a48f-474651f9e366)

In the mod's config screen, I turned off capturing entites and tried again, still the same result. To my understanding, having the following config should leave literally everything else but chunks information. Since I just want those blocks, is there a bug in this mod's configuration, or is it simply because of me doing something wrong?

![6](https://github.com/user-attachments/assets/6bb7c349-d640-4592-a149-fb52fa2502d3)

Logs: 
[capture.log](https://github.com/user-attachments/files/17268554/capture.log)

**Comment by Avanatiker** [comment]
No you are doing nothing wrong this is a bug. Due to some code changes it was forgotten to check for this setting again.
