### ISSUE TITLE
Maps Not Saved (1.21 Fabric)

### ISSUE THREAD

**Issue by APRme** [Avanatiker/WorldTools#47]
I tried to save some maps in an 1.21.1 server, but it didn't work.
<img width="622" alt="image_1" src="https://github.com/user-attachments/assets/a9b90cca-3e33-478f-ba33-340c291892f8">

**Comment by Avanatiker** [comment]
fixed here https://github.com/Avanatiker/WorldTools/releases/tag/1.2.5%2B1.21.1
