### ISSUE TITLE
ViaFabricPlus Support (Support for older servers and world formats)

### ISSUE THREAD

**Issue by BookWyrm114** [Avanatiker/WorldTools#5]
It would be great if the mod were to support using ViaFabricPlus to recognize when a user has joined a server older than the current game version, and have an option to save worlds from older servers in either the world format of the version the server is running, the version of the user (so ATM 1.20.x since that's the only version supported by this mod), or make 2 saves, one in each version. This would mean that, from the latest version of minecraft, WorldTools could be used to download worlds from any version of minecraft, including snapshot, pre-releases, April fools updates, etc. and save those worlds in a way that would allow them to be played in those older clients, rather than always being saved in 1.20.x (or above) format. This would also mean that this mod could be developed only for the latest version whilst working as a WDL mod for any multiplayer-compatible version of minecraft, including bedrock. (However conversion to bedrock shouldn't be a feature, as minecraft has a whole online tool for that, so instead, if a user joins and downloads a world from a bedrock server using ViaVersion and have the world format conversion feature enabled, it should notify them that they can use https://chunker.app/ to convert java worlds to bedrock if they so wish. This would also most likely require adding special support for much older versions, the experimental combat snapshots, and april fools updates especially, as they sometime have significant changes to the world and minecraft. So this is probably a more long-term goal as the mod is still in very early development.

**Comment by BookWyrm114** [comment]
tested out downloading a 1.12.2 world, seems to work fine but when saving I get this issue: 
<img width="675" alt="image" src="https://github.com/Avanatiker/WorldTools/assets/79489385/462b6b18-170b-40d7-bc39-6a84a35954e6">

**Comment by BookWyrm114** [comment]
so for the most part world downloads should be fine, you just need to add integration with ViaFabricPlus to properly get whatever server info it's trying to get, or get it to work properly with older servers. And then there's also saving the worlds in older world formats, but that's a whole other issue

**Comment by Avanatiker** [comment]
Will look into this thanks :)

**Comment by Avanatiker** [comment]
(maybe try with latest nightly the codebase has changed a lot)

**Comment by rfresh2** [comment]
Tested on a 1.12.2 server with VFP on latest dev build of WorldTools and it works fine

Resolving
