### ISSUE TITLE
ModMenu Support and config menu and various options

### ISSUE THREAD

**Issue by BookWyrm114** [Avanatiker/WorldTools#6]
Add a modmenu config, and populate the F12 options screen with a few basic options, most of which will also be available through modmenu:

1: Automatic World Downloading (Disabled by default) - decides whether or not the mod automatically starts downloading worlds upon join

2: Download Distance (locked to client's chunkloading distance by default) - decides the chunk radius around the player in which world data is downloaded, has 3 options: Custom, Client View Distance, and Server View Distance.

3: add buttons at the bottom of the screen to start World Downloading, Stop World Downloading, Clear Cache, and save data to disk. as well as freezing and unfreezing entities, and enabling/disabling chunk loading for a save, and resetting chunk data back to what the original save contained (world tools could save a small file in world saves containing a list of the chunks that were contained in the download, so if, for example, the world seed a user found through a seed-finding mod turns out to be incorrect, they can reset the chunk data and re-enter the seed.

4: Allow enabling or disabling saving of: Chunk data, storage data, sign/other block entity data, entity data, achievements, player data, player inventory data, ender chest data, villager trading/profession data, allay holding data, jukebox disc data, and various other options.

5: Allow manually setting the world seed

**Comment by Avanatiker** [comment]
A GUI was implemented now and you can try it in the latest nightly but it also will be released soon.
1. good idea
2. also good idea
3. buttons are implemented but the usability changed a bit to be more user friendly. custom world generator config is planned
4. implemented. detailed entity data like boat with chest or trades is planned (except what do you mean by the jukebox disc data and allay holding data?)
5. noted as well

**Comment by Avanatiker** [comment]
most of this is now implemented
