### ISSUE TITLE
World MetaData Not getting Saved

### ISSUE THREAD

**Issue by DraconicNEO** [Avanatiker/WorldTools#8]
Hi When I try to download worlds it doesn't save the metadata including the seed and all new chunks generate empty, is there any possible fix for this? I want to be able to download the world but also have it keep generating, rather than being completely empty.

**Comment by Avanatiker** [comment]
A feature for a custom world gen is planned.

**Comment by Avanatiker** [comment]
@DraconicNEO was added in 1.2.4
